
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: furkan1905
    url: jdbc:postgresql://localhost:5432/forum
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    show-sql: true

